[nfs]
172.31.20.184 ansible_ssh_user='ec2-user'

[webservers]
172.31.21.175 ansible_ssh_user='ec2-user'
172.31.28.189 ansible_ssh_user='ec2-user'

[db]
172.31.24.182 ansible_ssh_user='ubuntu' 

[lb]
172.31.27.6 ansible_ssh_user='ubuntu'